spring:
  application:
    name: PermTravelServer
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/permtravel
    username: postgres
    password: 1

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: permtravel