spring:
  application:
    name: PermTravelServer
  r2dbc:
    url: r2dbc:postgresql://iseletkov.yardtech.ru:50000/permtravel
    username: permtravel
    password: PermTravel()

minio:
  endpoint: http://iseletkov.yardtech.ru:50101
  access-key: permtravel
  secret-key: PermTravel()
  bucket: permtravel